package com.icbc.entity;

import com.icbc.turnpage.PageModel;

import java.io.Serializable;

public class TLogin extends PageModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.name
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.loginNum
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private String loginnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.password
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.user_id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.id
     *
     * @return the value of t_login.id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.id
     *
     * @param id the value for t_login.id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.name
     *
     * @return the value of t_login.name
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.name
     *
     * @param name the value for t_login.name
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.loginNum
     *
     * @return the value of t_login.loginNum
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public String getLoginnum() {
        return loginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.loginNum
     *
     * @param loginnum the value for t_login.loginNum
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setLoginnum(String loginnum) {
        this.loginnum = loginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.password
     *
     * @return the value of t_login.password
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.password
     *
     * @param password the value for t_login.password
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.user_id
     *
     * @return the value of t_login.user_id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.user_id
     *
     * @param userId the value for t_login.user_id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}