# 项目相关配置
iacmp:
  # 名称
  name: cms
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/wxy/uploadPath，Linux配置 /home/wxy/uploadPath）
  profile: ../upload
  # 获取ip地址开关
  addressEnabled: true