package com.icbc.entity;

import com.icbc.turnpage.PageModel;

import java.io.Serializable;

public class TTreeElementTree extends PageModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree_element_tree.id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree_element_tree.name
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree_element_tree.pid
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree_element_tree.order_sort
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private String orderSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree_element_tree.url
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tree_element_tree
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tree_element_tree.id
     *
     * @return the value of t_tree_element_tree.id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tree_element_tree.id
     *
     * @param id the value for t_tree_element_tree.id
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tree_element_tree.name
     *
     * @return the value of t_tree_element_tree.name
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tree_element_tree.name
     *
     * @param name the value for t_tree_element_tree.name
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tree_element_tree.pid
     *
     * @return the value of t_tree_element_tree.pid
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tree_element_tree.pid
     *
     * @param pid the value for t_tree_element_tree.pid
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tree_element_tree.order_sort
     *
     * @return the value of t_tree_element_tree.order_sort
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public String getOrderSort() {
        return orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tree_element_tree.order_sort
     *
     * @param orderSort the value for t_tree_element_tree.order_sort
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setOrderSort(String orderSort) {
        this.orderSort = orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tree_element_tree.url
     *
     * @return the value of t_tree_element_tree.url
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tree_element_tree.url
     *
     * @param url the value for t_tree_element_tree.url
     *
     * @mbg.generated Sat Jun 08 15:15:08 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }
}