
CREATE TABLE `im_access_system` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `CODE` varchar(32) DEFAULT NULL COMMENT '系统编码',
  `NAME` varchar(256) DEFAULT NULL COMMENT '系统名称',
  `AUTHENT_INFO` varchar(256) DEFAULT NULL COMMENT '身份验证信息',
  `REMARK` varchar(1024) DEFAULT NULL COMMENT '备注',
  `IP` varchar(256) DEFAULT NULL COMMENT '服务器地址',
  `SYS_FLAG_INT` int(4) NOT NULL COMMENT '系统标识',
  `ACC_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ACC_ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `SYS_FLAG_INT` (`SYS_FLAG_INT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_acs_log` (
  `ID` varchar(32) NOT NULL COMMENT '主键id',
  `IM_BATCH_ID` varchar(100) DEFAULT NULL COMMENT '批次主键',
  `OPERATOR_ID` varchar(500) DEFAULT NULL COMMENT '操作人id',
  `OPERATOR_ORGAN` varchar(500) DEFAULT NULL COMMENT '操作人机构',
  `OPERATE_TYPE` varchar(1) DEFAULT NULL COMMENT '操作类型（0-增；1-删;2-改）',
  `OPERATE_DATE` datetime DEFAULT NULL COMMENT '操作时间',
  `OPERATE_CONTEXT` text COMMENT '操作内容',
  `SYSTEM_FLAG` varchar(32) DEFAULT NULL COMMENT '系统标识',
  `REGBILLGLIDENO` varchar(100) DEFAULT NULL COMMENT '单据登记流水号',
  `FILE_TYPE` varchar(2) DEFAULT NULL COMMENT '文件类型',
  `FILE_NAME` varchar(500) DEFAULT NULL COMMENT '文件名称',
  `ACS_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ACS_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `IM_ACS_LOG_INDEX0` (`OPERATE_DATE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `im_customer_busino` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_CODE` varchar(100) DEFAULT NULL COMMENT '客户号',
  `BUSINO` text DEFAULT NULL COMMENT '影像流水号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `im_transaction_busino` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TRANSACTION_NO` varchar(100) DEFAULT NULL COMMENT '关联业务流水号',
  `BUSINO` text DEFAULT NULL COMMENT '影像流水号',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `im_annotation` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `CONTENT` varchar(2000) DEFAULT NULL COMMENT '内容',
  `CREAT_USER_NAME` varchar(100) DEFAULT NULL COMMENT '创建人名字',
  `CREAT_USER_ID` varchar(32) DEFAULT NULL COMMENT '创建人ID',
  `CREAT_DATE` date DEFAULT NULL COMMENT '创建时间',
  `X1` varchar(100) DEFAULT NULL COMMENT '坐标X1',
  `X2` varchar(100) DEFAULT NULL COMMENT '坐标X2',
  `Y1` varchar(100) DEFAULT NULL COMMENT '坐标Y1',
  `Y2` varchar(100) DEFAULT NULL COMMENT '坐标Y2',
  `IMAGE_ID` varchar(32) DEFAULT NULL COMMENT '关联图片',
  `IMG_W` varchar(32) DEFAULT NULL COMMENT '保存批注时画布的宽度',
  `IMG_H` varchar(32) DEFAULT NULL COMMENT '保存批注时画布的高度',
  `ANN_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ANN_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE `im_batch` (
  `ID` varchar(32) NOT NULL COMMENT '批次id',
  `REGBILLGLIDENO` varchar(64) DEFAULT NULL COMMENT '单据登记流水号',
  `OPERATIONCODE` varchar(64) NOT NULL DEFAULT '' COMMENT '业务编号',
  `TELLERNO` varchar(500) DEFAULT NULL COMMENT '操作柜员编号',
  `TELLERNAME` varchar(500) DEFAULT NULL COMMENT '操作柜员姓名',
  `BRANCHNO` varchar(500) DEFAULT NULL COMMENT '机构号',
  `BRANCHNAME` varchar(500) DEFAULT NULL COMMENT '机构名称',
  `SERIALNO` varchar(500) DEFAULT NULL COMMENT '顺序码',
  `RCVNUM` varchar(500) DEFAULT NULL COMMENT '正本数量',
  `TOTALNUM` varchar(500) DEFAULT '0' COMMENT '副本数量',
  `BILLPACKAGES` varchar(2000) DEFAULT NULL COMMENT '套数',
  `SYSTEMFLAG` varchar(100) DEFAULT NULL COMMENT '系统标识',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '批次创建时间',
  `OCR_FLAG` varchar(10) DEFAULT NULL COMMENT '识别标示(0-不识别;1-识别;2-已识别;)',
  `DEFECT_TYPE` varchar(2000) DEFAULT NULL COMMENT '类型缺失登记',
  `ORDER_NUM` varchar(500) DEFAULT NULL COMMENT '订单号',
  `b_hour` int(11) DEFAULT NULL COMMENT '小时',
  `b_year` int(11) DEFAULT NULL COMMENT '年份',
  `b_month` int(11) DEFAULT NULL COMMENT '月份',
  `b_day` int(11) DEFAULT NULL COMMENT '日期',
  `SYS_FLAG_INT` int(4) NOT NULL DEFAULT '0' COMMENT '系统标识状态',
  `USER_ASSCIATION_FLAG` int(4) DEFAULT '0' COMMENT '用户管理标识',
  `BATCH_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_CODE` varchar(50) DEFAULT NULL,
  `USER_NAME` varchar(50) DEFAULT NULL,
  `ID_CARD` varchar(50) DEFAULT NULL,
  `USER_ID` varchar(32) DEFAULT NULL,
  `TRANSACTION_NO` varchar(50) DEFAULT NULL,
  `CARD_TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`BATCH_ID`),
  UNIQUE KEY `OPERATIONCODE` (`OPERATIONCODE`),
  UNIQUE KEY `ID` (`ID`),
  KEY `index01` (`SYSTEMFLAG`,`CREATE_TIME`) USING BTREE,
  KEY `IM_BATCH_INDEX1` (`REGBILLGLIDENO`) USING BTREE,
  KEY `IM_BATCH_INDEX2` (`CREATE_TIME`) USING BTREE,
  KEY `USER_ID` (`USER_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_batch_im_bill` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `IM_BILL_ID` varchar(32) DEFAULT NULL COMMENT '单据类型外键',
  `IM_BATCH_ID` varchar(32) DEFAULT NULL COMMENT '批次外键',
  `BILL_BATCH_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`BILL_BATCH_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `im_bill` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `NAME` varchar(200) DEFAULT NULL COMMENT '类型名称',
  `CODE` varchar(32) DEFAULT NULL COMMENT '类型变那么',
  `SYS_ID` varchar(32) DEFAULT NULL COMMENT '关联系统',
  `PARENT_ID` varchar(32) DEFAULT NULL COMMENT '父节点',
  `BILL_ORDER` decimal(8,0) DEFAULT NULL COMMENT '类型顺序',
  `SYS_CODE` varchar(200) DEFAULT NULL COMMENT '系统编码',
  `IS_LOST_TYPE` varchar(4) DEFAULT NULL COMMENT '是否为缺失影像',
  `IS_LEAF` varchar(4) DEFAULT NULL COMMENT '是否为叶子节点',
  `PRODUCT` varchar(4) DEFAULT NULL COMMENT '所属产品',
  `BILL_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DICT_CODE` varchar(100) DEFAULT NULL COMMENT '字典编码',
  PRIMARY KEY (`BILL_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `ss` (`PARENT_ID`) USING BTREE,
  KEY `222` (`SYS_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_block` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `CODE` varchar(32) DEFAULT NULL COMMENT '切片编码',
  `NAME` varchar(500) DEFAULT NULL COMMENT '切片名称',
  `TEMPLATE_BLOCK_ID` varchar(32) DEFAULT NULL COMMENT '所属切片类型',
  `ECM_FILE_ID` varchar(500) DEFAULT NULL COMMENT 'ECM系统文件ID',
  `IMAGE_ID` varchar(32) DEFAULT NULL COMMENT '所属影像Id',
  `OCRVALUE` varchar(2000) DEFAULT NULL COMMENT '识别结果',
  `STATUS` varchar(10) DEFAULT NULL COMMENT '识别结果',
  `INPUT_VALUE` varchar(2000) DEFAULT NULL COMMENT '识别结果',
  `BLOCK_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`BLOCK_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `im_busino` (
  `ID` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BUSINO` varchar(100) DEFAULT NULL COMMENT '文件名异常流水号',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='异常流水表';


CREATE TABLE `im_dict` (
  `ID` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DICT_CODE` varchar(100) DEFAULT NULL COMMENT '字典编码',
  `DICT_NAME` varchar(100) DEFAULT NULL COMMENT '字典名称',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='分类字典表';

CREATE TABLE `im_file` (
  `ID` varchar(32) NOT NULL,
  `FILE_NAME` varchar(500) DEFAULT NULL COMMENT '文件名称',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '文件状态（0-正常；1-已废弃）',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '文件批次',
  `CREATE_TIME` date DEFAULT NULL COMMENT '上传时间',
  `SERIALNO` decimal(38,0) DEFAULT NULL COMMENT '文件顺序',
  `FILE_PATH` varchar(2000) DEFAULT NULL COMMENT '文件存放路径',
  `FILE_SIZE` decimal(9,0) DEFAULT NULL,
  `FILE_TYPE` varchar(32) DEFAULT NULL COMMENT '文件类型',
  `BILL_ID` varchar(32) DEFAULT NULL COMMENT '所属单据类型',
  `BILL_NAME` varchar(2000) DEFAULT NULL COMMENT '单据类型名称',
  `REMARK` varchar(2000) DEFAULT NULL COMMENT '备注',
  `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '上传人编号',
  `CREATE_USER_NAME` varchar(1000) DEFAULT NULL COMMENT '上传人名称',
  `SYSTEM_FLAG` varchar(100) DEFAULT NULL COMMENT '所属系统（用于分表）',
  `FILE_SOURCE` varchar(1000) DEFAULT NULL COMMENT '文件来源',
  `sys_flag_int` int(4) NOT NULL COMMENT '系统标识状态',
  `FILE_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_CODE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`FILE_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `3333333` (`BATCH_ID`) USING BTREE,
  KEY `IM_BATCH_INDEX1` (`BATCH_ID`) USING BTREE,
  KEY `IM_FILE_INDEX2` (`CREATE_TIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_hadoop_batch` (
  `ID` varchar(32) NOT NULL COMMENT '批次id',
  `REGBILLGLIDENO` varchar(64) DEFAULT NULL COMMENT '单据登记流水号',
  `OPERATIONCODE` varchar(64) NOT NULL DEFAULT '' COMMENT '业务编号',
  `TELLERNO` varchar(500) DEFAULT NULL COMMENT '操作柜员编号',
  `TELLERNAME` varchar(500) DEFAULT NULL COMMENT '操作柜员姓名',
  `BRANCHNO` varchar(500) DEFAULT NULL COMMENT '机构号',
  `BRANCHNAME` varchar(500) DEFAULT NULL COMMENT '机构名称',
  `SERIALNO` varchar(500) DEFAULT NULL COMMENT '顺序码',
  `RCVNUM` varchar(500) DEFAULT NULL COMMENT '正本数量',
  `TOTALNUM` varchar(500) DEFAULT NULL COMMENT '副本数量',
  `BILLPACKAGES` varchar(2000) DEFAULT NULL COMMENT '套数',
  `SYSTEMFLAG` varchar(100) DEFAULT NULL COMMENT '系统标识',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '批次创建时间',
  `OCR_FLAG` varchar(10) DEFAULT NULL COMMENT '识别标示(0-不识别;1-识别;2-已识别;)',
  `DEFECT_TYPE` varchar(2000) DEFAULT NULL COMMENT '类型缺失登记',
  `ORDER_NUM` varchar(500) DEFAULT NULL COMMENT '订单号',
  `b_hour` int(11) DEFAULT NULL COMMENT '小时',
  `b_year` int(11) DEFAULT NULL COMMENT '年份',
  `b_month` int(11) DEFAULT NULL COMMENT '月份',
  `b_day` int(11) DEFAULT NULL COMMENT '日期',
  `SYS_FLAG_INT` int(4) NOT NULL DEFAULT '0' COMMENT '系统标识状态',
  `USER_ASSCIATION_FLAG` int(4) DEFAULT '0' COMMENT '用户管理标识',
  `HBATCH_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`HBATCH_ID`),
  UNIQUE KEY `OPERATIONCODE` (`OPERATIONCODE`),
  UNIQUE KEY `ID` (`ID`),
  KEY `index01` (`SYSTEMFLAG`,`CREATE_TIME`) USING BTREE,
  KEY `IM_BATCH_INDEX1` (`REGBILLGLIDENO`) USING BTREE,
  KEY `IM_BATCH_INDEX2` (`CREATE_TIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_hadoop_upload_log` (
  `id` varchar(36) NOT NULL COMMENT '逻辑主键',
  `imageId` varchar(36) DEFAULT NULL COMMENT '影像ID',
  `imagePath` varchar(255) DEFAULT NULL COMMENT '影像路径',
  `upload_flag` int(4) DEFAULT NULL COMMENT '用户管理标识',
  `upload_time` datetime DEFAULT NULL COMMENT '上传时间',
  `upload_overtime` datetime DEFAULT NULL COMMENT '用户管理标识',
  `fail_count` int(4) DEFAULT NULL COMMENT '文件数量',
  `system_flag` varchar(64) DEFAULT NULL COMMENT '系统标识',
  `fail_reason` varchar(255) DEFAULT NULL COMMENT '文件来源',
  `fileSize` int(11) DEFAULT NULL COMMENT '文件大小',
  `fileType` int(2) DEFAULT NULL COMMENT '文件类型',
  `IMAGENAME` varchar(255) DEFAULT NULL COMMENT '影像名称',
  `isSmall` int(4) DEFAULT NULL COMMENT '文件是否为小',
  `HLOG_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`HLOG_ID`),
  UNIQUE KEY `ID` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_hadoop_video` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `VIDEO_NAME` varchar(500) DEFAULT NULL COMMENT '视频名称',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '视频状态（0-正常；1-已废弃）',
  `VIDEO_BILL` varchar(1) DEFAULT NULL COMMENT '视频类别（0-双录视频；1-安防视频）',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '视频批次',
  `CREATE_TIME` date DEFAULT NULL COMMENT '上传时间',
  `SERIALNO` decimal(38,0) DEFAULT NULL COMMENT '视频顺序',
  `VIDEO_PATH` varchar(2000) DEFAULT NULL COMMENT '视频存放路径',
  `VIDEO_SIZE` decimal(8,0) DEFAULT '0' COMMENT '视频大小',
  `VIDEO_TYPE` varchar(32) DEFAULT NULL COMMENT '视频类型',
  `REMARK` varchar(2000) DEFAULT NULL COMMENT '备注',
  `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '上传人编号',
  `CREATE_USER_NAME` varchar(1000) DEFAULT NULL COMMENT '上传人名称',
  `SYSTEM_FLAG` varchar(100) DEFAULT NULL COMMENT '所属系统（用于分表）',
  `VIDEO_SOURCE` varchar(1000) DEFAULT NULL COMMENT '视频来源',
  `sys_flag_int` int(4) NOT NULL COMMENT '影像标识状态',
  `VIDEO_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`VIDEO_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `3333333` (`BATCH_ID`) USING BTREE,
  KEY `IM_BATCH_INDEX1` (`BATCH_ID`) USING BTREE,
  KEY `IM_FILE_INDEX2` (`CREATE_TIME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_image` (
  `ID` varchar(32) NOT NULL COMMENT '影像主键',
  `IMAGE_NAME` varchar(500) DEFAULT NULL COMMENT '影像名称',
  `STATUS` varchar(1) DEFAULT NULL COMMENT '影像状态（0-正常；1-已废弃）',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '批次ID',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '影像上传时间',
  `SERIALNO` decimal(38,0) DEFAULT NULL COMMENT '影像顺序',
  `ECM_FILE_ID` varchar(2000) DEFAULT NULL COMMENT 'ECM系统文件ID',
  `WIDTH` varchar(100) DEFAULT NULL COMMENT '影像宽度',
  `HEIGHT` varchar(100) DEFAULT NULL COMMENT '影像高度',
  `BILL_ID` varchar(32) DEFAULT NULL COMMENT '单据类型',
  `COMPRESS_FILE_ID` varchar(2000) DEFAULT NULL COMMENT 'ECM的压缩图片文件ID',
  `TEMPLATE_ID` varchar(32) DEFAULT NULL COMMENT '影像模版ID',
  `IMAGE_SIZE` decimal(8,0) DEFAULT '0' COMMENT '影像大小',
  `IMAGE_PATH` varchar(2000) DEFAULT NULL COMMENT '影像存放路径',
  `OCR_RESULT` longtext COMMENT '识别结果',
  `OCR_STATUS` varchar(10) DEFAULT NULL COMMENT '识别状态(0-待识别;1-已识别;)',
  `BILL_NAME` varchar(500) DEFAULT NULL COMMENT '单据类型名称',
  `REMARK` varchar(2000) DEFAULT NULL COMMENT '备注',
  `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '上传人编号',
  `CREATE_USER_NAME` varchar(1000) DEFAULT NULL COMMENT '上传人名称',
  `DELETE_TIME` datetime DEFAULT NULL COMMENT '删除时间',
  `SYSTEM_FLAG` varchar(100) DEFAULT NULL COMMENT '所属系统（用于分区使用）',
  `DELETE_USER` varchar(64) DEFAULT NULL COMMENT '删除人编号',
  `DELETE_USER_NAME` varchar(64) DEFAULT NULL COMMENT '删除人姓名',
  `PZ_NUM` int(38) DEFAULT '0' COMMENT '批注数量',
  `IMAGE_SOURCE` varchar(1000) DEFAULT NULL COMMENT '影像来源',
  `SYS_FLAG_INT` int(4) NOT NULL COMMENT '系统标识状态',
  `OCR_TYPE` varchar(64) DEFAULT NULL COMMENT '识别类型',
  `IMAGE_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_CODE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`IMAGE_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `IM_IMAGE_INDEX1` (`BATCH_ID`) USING BTREE,
  KEY `IM_IMAGE_INDEX0` (`CREATE_TIME`,`IMAGE_SIZE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_image_cache` (
  `ID` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `IMAGE_NAME` varchar(500) DEFAULT NULL COMMENT '影像名称',
  `IMAGE_STATUS` varchar(1) DEFAULT NULL COMMENT '影像状态（0-正常；1-已废弃;2-待上传；3-正在上传；4-没有文件；5-上传错误；6-上传成功）',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '批次ID',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '影像上传时间',
  `SERIALNO` decimal(38,0) DEFAULT NULL COMMENT '影像顺序',
  `ECM_FILE_ID` varchar(2000) DEFAULT NULL COMMENT 'ECM系统文件ID',
  `WIDTH` varchar(100) DEFAULT NULL COMMENT '影像宽度',
  `HEIGHT` varchar(100) DEFAULT NULL COMMENT '影像高度',
  `BILL_ID` varchar(32) DEFAULT NULL COMMENT '单据类型',
  `COMPRESS_FILE_ID` varchar(2000) DEFAULT NULL COMMENT 'ECM的压缩图片文件ID',
  `TEMPLATE_ID` varchar(32) DEFAULT NULL COMMENT '影像模版ID',
  `IMAGE_SIZE` decimal(8,0) DEFAULT '0' COMMENT '影像大小',
  `IMAGE_PATH` varchar(2000) DEFAULT NULL COMMENT '影像存放路径',
  `OPERATIONCODE` varchar(100) DEFAULT NULL COMMENT '识别结果',
  `FILE_TYPE` varchar(100) DEFAULT NULL COMMENT '识别状态(0-待识别;1-已识别;)',
  `BILL_NAME` varchar(500) DEFAULT NULL COMMENT '单据类型名称',
  `REMARK` varchar(2000) DEFAULT NULL COMMENT '备注',
  `CREATE_USER` varchar(100) DEFAULT NULL COMMENT '上传人编号',
  `CREATE_USER_NAME` varchar(1000) DEFAULT NULL COMMENT '上传人名称',
  `DELETE_TIME` datetime DEFAULT NULL COMMENT '删除时间',
  `SYSTEM_FLAG` varchar(100) DEFAULT NULL COMMENT '所属系统（用于分区使用）',
  `DELETE_USER` varchar(64) DEFAULT NULL COMMENT '删除人编号',
  `DELETE_USER_NAME` varchar(64) DEFAULT NULL COMMENT '删除人姓名',
  `PZ_NUM` int(38) DEFAULT '0' COMMENT '批注数量',
  `IMAGE_SOURCE` varchar(1000) DEFAULT NULL COMMENT '影像来源',
  `SYS_FLAG_INT` int(4) NOT NULL COMMENT '系统标识状态',
  `OCR_TYPE` varchar(64) DEFAULT NULL COMMENT '识别类型',
  `IMAGE_ID` varchar(50) NOT NULL COMMENT '影像ID',
  `user_code` varchar(255) DEFAULT NULL COMMENT '客户号',
  `IP` varchar(30) DEFAULT NULL COMMENT '主机IP',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='异步影像表';


CREATE TABLE `im_image_lost_log` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '批次ID',
  `OPER_NO` varchar(500) DEFAULT NULL COMMENT '操作人工号',
  `OPER_TIME` date DEFAULT NULL COMMENT '操作时间',
  `LOST_BILLTYPE` varchar(2000) DEFAULT NULL COMMENT '缺失类型',
  `LOST_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`LOST_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `im_ocr` (
  `id` varchar(64) NOT NULL COMMENT '逻辑主键',
  `image_id` varchar(64) DEFAULT NULL COMMENT '影像id',
  `workitem_id` varchar(64) DEFAULT NULL COMMENT '识别id',
  `ocr_result` varchar(4) DEFAULT NULL COMMENT '识别结果',
  `ocr_info` longtext COMMENT '识别信息',
  `OCR_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`OCR_ID`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `workitem_id_UNIQUE` (`workitem_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_remark` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `CONTENT` varchar(2000) DEFAULT NULL COMMENT '内容',
  `CREAT_USER_ID` varchar(32) DEFAULT NULL COMMENT '创建人ID',
  `CREAT_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREAT_USER_NAME` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
  `BATCH_ID` varchar(500) DEFAULT NULL COMMENT '批次主键',
  `REMARK_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`REMARK_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_template_block_def` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `CODE` varchar(32) DEFAULT NULL COMMENT '切片编码',
  `NAME` varchar(32) DEFAULT NULL COMMENT '切片名称',
  `TEMPLATE_ID` varchar(32) DEFAULT NULL COMMENT '所属模版定义',
  `PYSZM` varchar(500) DEFAULT NULL COMMENT '拼音首字母',
  `BTDEF_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`BTDEF_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_template_def` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `CODE` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `NAME` varchar(500) DEFAULT NULL COMMENT '模版名称',
  `PYSZM` varchar(500) DEFAULT NULL COMMENT '拼音首字母',
  `TDEF_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`TDEF_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `im_user` (
  `ID` bigint(32) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_CODE` varchar(50) DEFAULT NULL COMMENT '客户号',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '客户姓名',
  `ID_CARD` varchar(50) DEFAULT NULL COMMENT '客户证件号码',
  `CARD_TYPE` varchar(20) DEFAULT NULL COMMENT '证件类型',
  `BIZ1` varchar(50) DEFAULT NULL COMMENT '预留字段1',
  `BIZ2` varchar(50) DEFAULT NULL COMMENT '预留字段2你',
  PRIMARY KEY (`ID`),
  KEY `index_user_code` (`USER_CODE`),
  KEY `index_user_three` (`USER_NAME`,`ID_CARD`,`CARD_TYPE`),
  KEY `index_user_four` (`USER_NAME`,`ID_CARD`,`CARD_TYPE`,`USER_CODE`),
  KEY `index_id_card` (`ID_CARD`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='客户信息表';


CREATE TABLE `m_worker_node` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
  `HOST_NAME` varchar(64) NOT NULL COMMENT 'host name',
  `PORT` varchar(64) NOT NULL COMMENT 'port',
  `TYPE` int(11) NOT NULL COMMENT 'node type: ACTUAL or CONTAINER',
  `LAUNCH_DATE` date NOT NULL COMMENT 'launch date',
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'modified time',
  `CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'created time',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='DB WorkerID Assigner for UID Generator';


CREATE TABLE `phone_user` (
  `ID` varchar(32) NOT NULL COMMENT '用户主键',
  `USER_NAME` varchar(500) NOT NULL COMMENT '用户名称',
  `USER_CODE` varchar(500) NOT NULL COMMENT '用户编码',
  `PHONE_NUM` varchar(11) NOT NULL COMMENT '电话号码',
  `TOKEN` varchar(500) NOT NULL COMMENT '验证密匙',
  `USER_PASS` varchar(500) NOT NULL COMMENT '用户密码',
  `PUSER_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`PUSER_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `phone_version` (
  `ID` varchar(64) NOT NULL COMMENT '主键id',
  `VERSION_NO` varchar(64) DEFAULT NULL COMMENT '版本号',
  `URL` varchar(255) DEFAULT NULL COMMENT '版本更新地址',
  `TITLE` varchar(255) DEFAULT NULL COMMENT '版本更新说明',
  `STATE` varchar(32) DEFAULT NULL COMMENT '“1”强制更新，”0“非强制更新',
  `FLAG` varchar(32) DEFAULT NULL COMMENT '”1“最新版本，”0“旧版本',
  `PHONE_TYPE` varchar(32) DEFAULT NULL COMMENT '"ios"或”android“',
  `PVERSION_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`PVERSION_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sm_menu` (
  `CODE` varchar(30) NOT NULL COMMENT '菜单编码',
  `NAME` varchar(60) DEFAULT NULL COMMENT '菜单名称',
  `INDEX_NO` decimal(8,0) DEFAULT NULL COMMENT '菜单顺序',
  `URL` varchar(255) NOT NULL COMMENT '菜单URL地址',
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `PARENT_ID` varchar(32) DEFAULT NULL COMMENT '父菜单id',
  `PATH` varchar(100) DEFAULT NULL COMMENT '路径',
  `ALL_URLS` varchar(4000) DEFAULT NULL COMMENT '包含所有URL',
  `MENU_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`MENU_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `sm_organ` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `CODE` varchar(9) NOT NULL COMMENT '机构代码',
  `NAME` varchar(512) NOT NULL COMMENT '机构名称',
  `PARENT_ID` varchar(32) DEFAULT NULL COMMENT '父机构',
  `PATH` varchar(200) DEFAULT NULL COMMENT '机构路径',
  `STATUS` decimal(2,0) DEFAULT NULL COMMENT '机构状态（0-正常;1-停用）',
  `MODIFIER` varchar(12) DEFAULT NULL COMMENT '修改人',
  `CREATOR` varchar(12) DEFAULT NULL COMMENT '创建人',
  `SSO_ORG_CODE` varchar(9) DEFAULT NULL COMMENT '管理机构号',
  `ORGAN_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ORGAN_ID`),
  UNIQUE KEY `ID` (`ID`) USING BTREE,
  KEY `UK_SM_ORGAN` (`CODE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `sm_param` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `NAME` varchar(500) DEFAULT NULL COMMENT '参数名称',
  `VALUE` varchar(500) DEFAULT NULL COMMENT '参数值',
  `CODE` varchar(32) DEFAULT NULL COMMENT '参数编码',
  `PARAM_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`PARAM_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `sm_role` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `CODE` varchar(32) NOT NULL COMMENT '角色代码',
  `NAME` varchar(50) NOT NULL COMMENT '角色名称',
  `STATUS` decimal(2,0) NOT NULL DEFAULT '0' COMMENT '角色状态（0-正常；1-停用）',
  `TYPE` varchar(10) DEFAULT '01' COMMENT '角色类型（01-综合角色；02-特定角色；03=录入角色）',
  `GRAD` decimal(2,0) DEFAULT NULL COMMENT '角色等级',
  `HTML_CONTENT` varchar(4000) DEFAULT NULL COMMENT '备注(html编辑)',
  `ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `UNI_ROLE` (`CODE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `sm_role_menu` (
  `MENU_ID` varchar(32) NOT NULL COMMENT '菜单id',
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `ROLE_ID` varchar(32) NOT NULL COMMENT '角色id',
  `ROLE_MENU_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ROLE_MENU_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `UNI_ROLE_MENU` (`MENU_ID`,`ROLE_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `sm_user` (
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `CODE` varchar(32) DEFAULT NULL COMMENT '用户代码',
  `NAME` varchar(60) DEFAULT NULL COMMENT '用户名称',
  `ORG_ID` varchar(32) DEFAULT NULL COMMENT '所属机构',
  `PASSWORD` varchar(60) DEFAULT NULL COMMENT '密码',
  `TYPE` varchar(2) DEFAULT '01' COMMENT '类型',
  `STATUS` decimal(2,0) DEFAULT '0' COMMENT '用户状态（0-正常;99-停用）',
  `CREATE_TIME` date DEFAULT NULL COMMENT '创建时间',
  `LAST_PASS_CHG_DATE` date DEFAULT NULL COMMENT '最后密码修改日期',
  `LOGIN_IP` varchar(15) DEFAULT NULL COMMENT '当前登录ip',
  `PROJECT_ID` varchar(32) DEFAULT NULL COMMENT '所属项目',
  `PRO_EMPLOYEE_ID` varchar(32) DEFAULT NULL COMMENT '员工ID',
  `LAST_LOGIN` date DEFAULT NULL COMMENT '最后登录时间',
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `SM_USRE_UNIQUE` (`CODE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `sm_user_organ` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `USER_CODE` varchar(32) DEFAULT NULL COMMENT '用户代码',
  `ORGAN_CODE` varchar(32) DEFAULT NULL COMMENT '机构代码',
  `STATEDATE` date DEFAULT NULL COMMENT '开始时间',
  `ENDDATE` date DEFAULT NULL COMMENT '结束时间',
  `USER_ORGAN_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`USER_ORGAN_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sm_user_role` (
  `USER_ID` varchar(32) NOT NULL COMMENT '用户',
  `ID` varchar(32) NOT NULL COMMENT '逻辑主键',
  `ROLE_ID` varchar(32) NOT NULL COMMENT '角色',
  `USER_ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`USER_ROLE_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `web_service` (
  `ID` varchar(32) CHARACTER SET utf8 NOT NULL COMMENT '主键',
  `SYS_ID` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '客户端系统标识符',
  `OPERATIONCODE` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '受理号1（车承保时为交强号）',
  `REGBILLGLIDENO` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '受理号2（车承保时为商业号）',
  `ORDER_NUM` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '响应码（第三方上传使用）',
  `OPERA_TIME` datetime DEFAULT NULL COMMENT '接收报文时间',
  `SYS_KEY` varchar(500) CHARACTER SET utf8 DEFAULT NULL,
  `METHOD_TYPE` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '方法参数',
  `CONTENT` longtext CHARACTER SET utf8 COMMENT 'xml报文',
  `WEB_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`WEB_ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `sys_key` (`SYS_KEY`(255)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;


CREATE TABLE `work_item` (
  `ID` varchar(32) NOT NULL COMMENT '主键',
  `CODE` varchar(32) DEFAULT NULL COMMENT '业务编号',
  `NAME` varchar(300) DEFAULT NULL COMMENT '工作项名称',
  `STATUS` decimal(20,0) DEFAULT NULL COMMENT '状态（0-初始；1-就绪；3-已获取；4-已分配；10-已完成）',
  `DESCRIPTION` varchar(50) DEFAULT NULL COMMENT '工作项描述',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '工作项类型(OCR-OCR；人工版面分类-人工版面分类；切块-切块； 录入-录入；录入一级岗-录入一级岗；录入二级岗-录入二级岗；录入仲裁-录入仲裁；质检-质检；问题件-问题件；电话处理-电话处理；人工审核-人工审核；)',
  `ROLE` varchar(32) DEFAULT NULL COMMENT '录入角色（0-非中文；1-中文；2-录入一级岗；3-录入二级岗）',
  `OPERATOR` varchar(64) DEFAULT NULL COMMENT '任务操作员',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `FINISH_TIME` timestamp NULL DEFAULT NULL COMMENT '完成时间',
  `ACQUIRE_TIME` timestamp NULL DEFAULT NULL COMMENT '获取时间',
  `EX_OPERATOR1` varchar(32) DEFAULT NULL COMMENT '排除操作员1',
  `EX_OPERATOR2` varchar(32) DEFAULT NULL COMMENT '排除操作员2',
  `SCAN_BATCH_ID` varchar(32) DEFAULT NULL COMMENT '扫描批次',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '业务批次',
  `IMAGE_ID` varchar(32) DEFAULT NULL COMMENT '原始影像',
  `PRIORITY` decimal(22,0) DEFAULT NULL COMMENT '优先级（大数优先）',
  `BIZ_DATE` date DEFAULT NULL COMMENT '业务日期',
  `CH_WORKLOAD` decimal(5,0) DEFAULT '0' COMMENT '中文工作量',
  `EN_WORKLOAD` decimal(5,0) DEFAULT '0' COMMENT '英文工作量',
  `FIELD_NUM` decimal(5,0) DEFAULT '0' COMMENT '字段个数',
  `VALID_OPER` varchar(32) DEFAULT NULL COMMENT '指定操作员',
  `VALID_FIELD_NUM` decimal(5,0) DEFAULT '0' COMMENT '非空字段数',
  `PROJECT_ID` varchar(36) DEFAULT NULL COMMENT '所属项目',
  `BILL_ID` varchar(128) DEFAULT NULL COMMENT '所属单据',
  `PROCESS_TIME` decimal(12,0) DEFAULT NULL COMMENT '处理时间',
  `BATCH_CTIME` timestamp NULL DEFAULT NULL COMMENT '批次创建时间',
  `IMAGE_BLOCK_ID` varchar(32) DEFAULT NULL COMMENT '切块影像',
  `EX_WORK_ITEM_ID` varchar(32) DEFAULT NULL COMMENT '排除环节',
  `INPUT_NO` decimal(5,0) DEFAULT NULL COMMENT '第几次录入（1或2等）',
  `MONTH` decimal(6,0) DEFAULT NULL COMMENT '月份',
  `YEAR` decimal(5,0) DEFAULT NULL COMMENT '年份',
  `DAY` decimal(8,0) DEFAULT NULL COMMENT '日期',
  `OPERATOR_NAME` varchar(64) DEFAULT NULL COMMENT '操作员姓名',
  `QUEUE_NAME` varchar(32) DEFAULT NULL COMMENT '队列名',
  `OBTAINED_TIME` decimal(25,0) DEFAULT NULL COMMENT '获取时间',
  `UPDATE_ASS` varchar(32) DEFAULT NULL COMMENT '获取时间戳',
  `WORK_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`WORK_ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
